# Generated by Django 3.2.8 on 2021-10-10 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Type (e.g. Story, Comments, etc)', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_id', models.IntegerField(null=True, verbose_name='Story ID')),
                ('title', models.TextField(verbose_name='Story Title')),
                ('url', models.URLField(null=True, verbose_name='Story URL')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Story Author')),
                ('text', models.TextField(null=True, verbose_name='The Story')),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('time', models.DateTimeField(null=True, verbose_name='Date Story was created')),
                ('descendants', models.IntegerField(null=True, verbose_name='The total comments counted')),
                ('score', models.IntegerField(null=True, verbose_name="Story's score or the votes of a pollopt")),
                ('local_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('types', models.ManyToManyField(help_text='Pick a Type or Create a new Type', to='news.Types')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['title', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField(null=True, unique=True, verbose_name='Comment ID')),
                ('text', models.TextField(verbose_name='The Comment')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Comment Author')),
                ('time', models.DateTimeField(null=True, verbose_name='Date Comment was created')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.story')),
                ('types', models.ManyToManyField(help_text='Pick a Type or Create a new Type', to='news.Types')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
