# Generated by Django 3.2.8 on 2021-10-13 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_rename_types_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='local_author',
        ),
        migrations.RemoveField(
            model_name='story',
            name='text',
        ),
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
